const customers = [
  {
    PK: "customer",
    SK: "customer#1",
    id: "1",
    name: "John Doe",
    age: 30,
    email: "johndoe@gmail.com",
    address: "123 Main St",
    city: "New York",
    state: "NY",
    zip: "10001",
    phone: "123-456-7890",
  },
  {
    PK: "customer",
    SK: "customer#2",
    id: "2",
    name: "Mary Doe",
    age: 29,
    email: "marydoe@gmail.com",
    address: "123 Main St",
    city: "New York",
    state: "NY",
    zip: "10001",
    phone: "234-456-7890",
  },
  {
    PK: "customer",
    SK: "customer#3",
    id: "3",
    zip: "10001",
    address: "123 Main St",
    city: "New York",
    phone: "234-456-7890",
    name: "John Smith",
    state: "NY",
    age: 32,
    email: "johnsmith@gmail.com",
  },
  {
    PK: "customer",
    SK: "customer#4",
    id: "4",
    zip: "10001",
    address: "123 Main St",
    city: "New York",
    phone: "234-456-7890",
    name: "Mary Doe",
    state: "NY",
    age: 29,
    email: "marydoe@gmail.com",
  },

  {
    PK: "customer",
    SK: "customer#5",
    id: "5",
    zip: "10001",
    address: "123 Main St",
    city: "New York",
    phone: "234-456-7890",
    name: "Robert Johnson",
    state: "NY",
    age: 35,
    email: "robertjohnson@gmail.com",
  },
  {
    PK: "customer",
    SK: "customer#6",
    id: "6",
    zip: "10001",
    address: "123 Main St",
    city: "New York",
    phone: "234-456-7890",
    name: "Emily Wilson",
    state: "NY",
    age: 28,
    email: "emilywilson@gmail.com",
  },
  {
    PK: "customer",
    SK: "customer#7",
    id: "7",
    zip: "10001",
    address: "123 Main St",
    city: "New York",
    phone: "234-456-7890",
    name: "David Brown",
    state: "NY",
    age: 30,
    email: "davidbrown@gmail.com",
  },
  {
    PK: "customer",
    SK: "customer#8",
    id: "8",
    zip: "10001",
    address: "123 Main St",
    city: "New York",
    phone: "234-456-7890",
    name: "Sarah Davis",
    state: "NY",
    age: 27,
    email: "sarahdavis@gmail.com",
  },
  {
    PK: "customer",
    SK: "customer#9",
    id: "9",
    zip: "10001",
    address: "123 Main St",
    city: "New York",
    phone: "234-456-7890",
    name: "Michael Johnson",
    state: "NY",
    age: 33,
    email: "michaeljohnson@gmail.com",
  },
  {
    PK: "customer",
    SK: "customer#10",
    id: "10",
    zip: "10001",
    address: "123 Main St",
    city: "New York",
    phone: "234-456-7890",
    name: "Jessica Taylor",
    state: "NY",
    age: 31,
    email: "jessicataylor@gmail.com",
  },
  {
    PK: "customer",
    SK: "customer#11",
    id: "11",
    zip: "10001",
    address: "123 Main St",
    city: "New York",
    phone: "234-456-7890",
    name: "Daniel Anderson",
    state: "NY",
    age: 36,
    email: "danielanderson@gmail.com",
  },
  {
    PK: "customer",
    SK: "customer#12",
    id: "12",
    zip: "10001",
    address: "123 Main St",
    city: "New York",
    phone: "234-456-7890",
    name: "Olivia Martinez",
    state: "NY",
    age: 29,
    email: "oliviamartinez@gmail.com",
  },
];

module.exports = customers;
